# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta28
kind: Config
build:
#  googleCloudBuild:
#    projectId: dev-demo-project-366116
  local:
    tryImportMissing: true
    push: true
  tagPolicy:
    inputDigest: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
    - image: us-central1-docker.pkg.dev/dev-demo-project-366116/hello-repo/helloworld-gke
      # To learn more about how Jib builds Java containers visit
      # https://github.com/GoogleContainerTools/jib
      jib:
        args:
        - -Dmaven.test.skip=true

# defines the Kubernetes manifests to deploy on each run
profiles:
- name: dev
  deploy:
    kustomize:
      paths:
        - config-source/overlays/dev
- name: staging
  deploy:
    kustomize:
      paths:
        - config-source/overlays/staging
- name: production
  deploy:
    kustomize:
      paths:
        - config-source/overlays/production
