apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
spec:
  template:
    spec:
      containers:
      - name: hello-app
        image: us-central1-docker.pkg.dev/dev-demo-project-366116/hello-repo/helloworld-gke:b9116a7f2a89c740831061d892ad44cafc860f41ccd445f008803beb3e0b4c2b
        