apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
spec:
  template:
    spec:
      containers:
      - name: hello-app
        image: us-central1-docker.pkg.dev/dev-demo-project-366116/hello-repo/helloworld-gke:b79d104f1ca97d0fdc1c68009c350cad407b9954c2ff14d88594988608273c87
        